version: "2"
services:
        web:
                image: nginx:latest
                ports:
                        - "8080:80"
                volumes:
                        - ./barcoders:/var/www/barcoders
                        - ./site.conf:/etc/nginx/conf.d/site.conf
                links:
                        - php
        php:
                build: .
                ports:
                        - "9000:9000"
                volumes:
                        - ./barcoders:/var/www/barcoders
