version: "2"
services:
        web:
                image: nginx:latest
                ports: 
                        - "8080:80"
                volumes:
                        - ./barcoders:/var/www/barcoders
                        - ./build/nginx/site.conf:/etc/nginx/conf.d/site.conf
                links:
                        - php
        php:
                build: ./build/php
                volumes:
                        - ./barcoders:/var/www/barcoders
